### ISSUE TITLE
gem5 did not build

### ISSUE THREAD

**Issue by sammanthp007** [sammanthp007/gem5-tutorial#1]
`scons build/x86/gem5.opt -j5` gave error:
```
Building in /home/aos-ubuntu/development/gem5/build/x86
Error: cannot find variables file /home/aos-ubuntu/development/gem5/build/variables/x86 or default file(s) /home/aos-ubuntu/development/gem5/build_opts/x86
```

**Comment by sammanthp007** [comment]
It because you have `build/x86/gem5.opt` in your command but your `build_opt` directory has `X86` folder and not `x86`. 

Reference: [gem5 QA](http://qa.gem5.org/1488/newbie-how-do-i-fix-the-installation-error-shown-below)

**Comment by Liza-BB8** [comment]
The following compilation command gave this error (to use the network test):
Command: scons build/ALPHA_Network_test/gem5.opt
Error: Building in /home/sa_la/Téléchargements/gem5/build/ALPHA_Network_test
Error: cannot find variables file /home/sa_la/Téléchargements/gem5/build/variables/ALPHA_Network_test or default file(s) /home/sa_la/Téléchargements/gem5/build_opts/ALPHA_Network_test
